db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=${MYSQLUSER}
db.password=${MYSQLPASSWORD}

hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
